[features]
seeds = false

[programs.mainnet]
optifi_cpi = "optF8UCDznwL6mJ2UPF4jnHaHbJe5g9RY8CaU846noM"

[programs.devnet]
optifi_cpi = "opDV2tLVsRPGk9aYqm4gdtGotiRwjuYKUmWzWB7NfCR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
